#ifndef _CONFIG_H_MULTISYNCGUI
#define _CONFIG_H_MULTISYNCGUI

#define MULTISYNCGUI_VERSION "${MULTISYNCGUI_VERSION}"
#define MULTISYNCGUI_GLADE "${MULTISYNCGUI_GLADE}"
#define MULTISYNCGUI_ICON "${MULTISYNCGUI_ICON}"

#endif // _CONFIG_H_MULTISYNCGUI
