/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_syncpairwin (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_logwindow (void);
GtkWidget* create_mainwindow (void);
GtkWidget* create_duplicatewin (void);
