/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo dir_submenu_uiinfo[] =
{
  GNOMEUIINFO_END
};

GtkWidget*
create_synce_wnd_options (void)
{
  GtkWidget *synce_wnd_options;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *label15;
  GtkWidget *hbox1;
  GtkWidget *table1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label14;
  GtkWidget *txt_path;
  GtkWidget *optionmenu1;
  GtkWidget *dir_submenu;
  GtkWidget *e2hbox1;
  GtkWidget *e2label5;
  GtkWidget *e2hbox2;
  GtkWidget *e2label7;
  GtkWidget *e2hbox3;
  GtkWidget *e2label9;
  GtkWidget *hseparator10;
  GtkWidget *hbuttonbox2;
  GtkWidget *btn_cancel;
  GtkWidget *btn_ok;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  synce_wnd_options = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (synce_wnd_options, "synce_wnd_options");
  gtk_window_set_title (GTK_WINDOW (synce_wnd_options), "Preferences");
  gtk_window_set_destroy_with_parent (GTK_WINDOW (synce_wnd_options), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (synce_wnd_options), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 12);

  vbox2 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 6);

  label15 = gtk_label_new ("<span weight='bold'>Enter the directory to synchronize</span>");
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (vbox2), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, TRUE, 0);

  table1 = gtk_table_new (1, 3, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox1), table1, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 12);

  button1 = gtk_button_new ();
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_table_attach (GTK_TABLE (table1), button1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic ("List directories");
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);

  txt_path = gtk_entry_new ();
  gtk_widget_set_name (txt_path, "txt_path");
  gtk_widget_show (txt_path);
  gtk_table_attach (GTK_TABLE (table1), txt_path, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (txt_path, 40, 23);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_set_name (optionmenu1, "optionmenu1");
  gtk_widget_show (optionmenu1);
  gtk_box_pack_start (GTK_BOX (vbox2), optionmenu1, FALSE, FALSE, 0);

  dir_submenu = gtk_menu_new ();
  gtk_widget_set_name (dir_submenu, "dir_submenu");
  gnome_app_fill_menu (GTK_MENU_SHELL (dir_submenu), dir_submenu_uiinfo,
                       accel_group, FALSE, 0);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), dir_submenu);

  e2hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (e2hbox1, "e2hbox1");
  gtk_widget_show (e2hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), e2hbox1, FALSE, TRUE, 0);

  e2label5 = gtk_label_new ("    ");
  gtk_widget_set_name (e2label5, "e2label5");
  gtk_widget_show (e2label5);
  gtk_box_pack_start (GTK_BOX (e2hbox1), e2label5, FALSE, FALSE, 0);

  e2hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (e2hbox2, "e2hbox2");
  gtk_widget_show (e2hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), e2hbox2, FALSE, TRUE, 0);

  e2label7 = gtk_label_new ("    ");
  gtk_widget_set_name (e2label7, "e2label7");
  gtk_widget_show (e2label7);
  gtk_box_pack_start (GTK_BOX (e2hbox2), e2label7, FALSE, FALSE, 0);

  e2hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (e2hbox3, "e2hbox3");
  gtk_widget_show (e2hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), e2hbox3, FALSE, TRUE, 0);

  e2label9 = gtk_label_new ("    ");
  gtk_widget_set_name (e2label9, "e2label9");
  gtk_widget_show (e2label9);
  gtk_box_pack_start (GTK_BOX (e2hbox3), e2label9, FALSE, FALSE, 0);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator10, "hseparator10");
  gtk_widget_show (hseparator10);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator10, FALSE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 30);

  btn_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (btn_cancel, "btn_cancel");
  gtk_widget_show (btn_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), btn_cancel);
  gtk_widget_set_size_request (btn_cancel, 81, 32);

  btn_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (btn_ok, "btn_ok");
  gtk_widget_show (btn_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), btn_ok);
  gtk_widget_set_size_request (btn_ok, 81, 32);

  g_signal_connect ((gpointer) synce_wnd_options, "destroy",
                    G_CALLBACK (synce_on_wnd_options_destroy),
                    NULL);
  g_signal_connect ((gpointer) btn_cancel, "clicked",
                    G_CALLBACK (synce_on_btn_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_ok, "clicked",
                    G_CALLBACK (synce_on_btn_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (synce_wnd_options, synce_wnd_options, "synce_wnd_options");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, label15, "label15");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, table1, "table1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, button1, "button1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, image1, "image1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, label14, "label14");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, txt_path, "txt_path");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, optionmenu1, "optionmenu1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, dir_submenu, "dir_submenu");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2hbox1, "e2hbox1");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2label5, "e2label5");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2hbox2, "e2hbox2");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2label7, "e2label7");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2hbox3, "e2hbox3");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, e2label9, "e2label9");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, btn_cancel, "btn_cancel");
  GLADE_HOOKUP_OBJECT (synce_wnd_options, btn_ok, "btn_ok");

  gtk_window_add_accel_group (GTK_WINDOW (synce_wnd_options), accel_group);

  return synce_wnd_options;
}

